app:
  name: "Customer Satisfaction Analysis"
  version: "1.0.0"
  port: 8000

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  logfile: "logs/app.log"


model:
  model_path: "../models/model.pkl"